version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*", "-c", "hba_file=/var/lib/postgresql/data/pg_hba.conf"]
  
volumes:
  postgres_data:
